### ISSUE TITLE
Cannot calculate BERT embeddings under GPU environment

### ISSUE THREAD

**Issue by WinterShiver** [juntaoy/dali-full-anaphora#6]
My problem when running your code for your LREC20 paper: cannot calculate BERT embeddings under GPU environment. 
My environment: Titan XP, cuda 9.0. 
I have installed all the required packages under my Python environment, and done all the previous procedures successfully (including those in setup.sh and get_char_vocab.py). However when running extract_bert_features.sh, I have got:
```bash
(dali) [username@servername extract_bert_features]$ sh extract_bert_features.sh 
Traceback (most recent call last):
  File "extract_features.py", line 357, in <module>
    tf.app.run()
  File "/home/username/anaconda3/envs/dali/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "extract_features.py", line 270, in main
    is_per_host = tf.contrib.tpu.InputPipelineConfig.PER_HOST_V2
AttributeError: 'module' object has no attribute 'InputPipelineConfig'
```

Could you help me on this problem? Many thanks.

**Comment by juntaoy** [comment]
I think this error is related to the tf version, so BERT part needs a higher version of tenserflow, I use 1.12 in my case for extract BERT embeddings and the main model uses 1.8 version. This means you will need setup another conda env for BERT

**Comment by WinterShiver** [comment]
Issue fixed. Thank you!
